graph LR
    Read(Read Data) --> B(Convert)
    B --> C(Parse)
    C --> Write(Write to DB)
    Write --> E(Cleanup)

%% Status: 2025-10-04T21:00:00Z
%% Read: Success (2000s)
%% B: Failed (18s)
%% C: Failed (180s)
%% Write: Failed (5s)
%% E: Running (500s)