graph LR
    Read(Read Data) --> B(Convert)
    B --> C(Parse)
    C --> Write(Write to DB)
    Write --> E(Cleanup)

%% Status: 2025-10-04T22:00:00Z
%% Read: Success (2000s)
%% B: Failed (18s)
%% C: Success (180s)
%% Write: Running (14s)
%% E: Waiting (100s)