graph LR
    Read(Read Data) --> B(Convert)
    B --> C(Parse)
    C --> Write(Write to DB)
    Write --> E(Cleanup)

%% Status: 2025-10-04T15:00:00Z
%% Read: Success (345s)
%% B: Success (4s)
%% C: Running (160s)
%% Write: Waiting (0s)
%% E: Waiting (0s)